function onEvent()
	noteTweenAlpha("note yeah", 0, 0.2, 1, "linear")
	noteTweenAlpha("LOL", 1, 0.2, 1, "linear")
	noteTweenAlpha("why u lookin", 2, 0.2, 1, "linear")
	noteTweenAlpha("maze", 3, 0.2, 1, "linear")
	noteTweenAlpha("dave n bambi", 4, 0.2, 1, "linear")
	noteTweenAlpha("odd noise intesifies", 5, 0.2, 1, "linear")
	noteTweenAlpha("note", 6, 0.2, 1, "linear")
	noteTweenAlpha("susy bitch", 7, 0.2, 1, "linear")
end